### ISSUE TITLE
Brandon's Invalid Issue

### ISSUE THREAD

**Issue by BrandonBirchallUK** [Blinkaji/BookmakersReports#1]
N/A

**Comment by PatrickFarnworth** [comment]
Hello Brandon, I didn't find this review very useful, when I arrived at the restaurant I was greeted by lovely staff who were very nice to me and didn't at all fondle my crotch as you claimed they did. It's immature to be posting fake reviews in TripAdvisor as it can really damage small business's reputations. Get a life you smelly wimp!

**Comment by Blinkaji** [comment]
Meme
