### ISSUE TITLE
It's Not Complete Shit

### ISSUE THREAD

**Issue by PatrickFarnworth** [Blinkaji/BookmakersReports#2]
Yo there Lloydy boy!

**Comment by PatrickFarnworth** [comment]
Issues time:

**Comment by PatrickFarnworth** [comment]
Issue One so far (doing this in real time): 
I don't like how it feeds back the result of a search too much, cos returning the row number isn't a very user friendly way.

**Comment by PatrickFarnworth** [comment]
Issue 2:
The names are cut off a lot, which makes it tougher to see what's going on on there.

**Comment by PatrickFarnworth** [comment]
Issue Three:

**Comment by PatrickFarnworth** [comment]
The interface is really gud

**Comment by PatrickFarnworth** [comment]
When I altered the odds for a Horse and pressed "Save Changes", some bad shit happened and the payout didn't change,

**Comment by PatrickFarnworth** [comment]
^^ Issue For

**Comment by PatrickFarnworth** [comment]
>Issue 5
>
>If I move the window to a different place on the screen and then make an update, the window jumps 
>back to where is was before.

**Comment by PatrickFarnworth** [comment]
Issue 6:
I'm not sure how you're working out best case and worst case scenario, but it seems to be just based on highest and lowest payout. That's cool but it doesn't account for the size of the bet made. I made a £50000 bet on a horse, and if that horse won it would probably be really bad for the company, but this horse did not show as the worst-case scenario.

**Comment by PatrickFarnworth** [comment]
Alright, that's all I could find, it's a neat little concise interface, top notch stuff Llwyd!!!! Lovin' it, keep up thegood, you inspire me.

Peace out,

The Cauliflower Collector who works in the Spar on Monday evenings.

**Comment by Blinkaji** [comment]
Added to Other Issue Categories
