### ISSUE TITLE
Functionality Issues

### ISSUE THREAD

**Issue by Blinkaji** [Blinkaji/BookmakersReports#4]
Patrick:
- Best/Worst Scenario Is Coded Like Really Weirdly and I genuinely Forgot How I Coded It
- Payout Doesn't Save
- Search Makes it Unclear When Horse is Not Present
- Change File Sometimes Works?
- Validation Not Consistent
- Bets Maybe Capped at 30?

**Comment by BrandonBirchallUK** [comment]
Yes quite

**Comment by Blinkaji** [comment]
Sid: Click OK Twice to Ignore Validation

**Comment by Blinkaji** [comment]
Sid: Multiple Deletions Don't Work

**Comment by Blinkaji** [comment]
Sid: Try Saving after Deleting Loads?

**Comment by Blinkaji** [comment]
Sid: Validation not Case Sensetive

**Comment by Blinkaji** [comment]
Sid: Negative Bet Values

**Comment by Blinkaji** [comment]
Sid: Set Tables to Non Editable

**Comment by Blinkaji** [comment]
Maybe Add Bet Through Horse Tab

**Comment by Blinkaji** [comment]
Sid: Cannot Change Horse Odds

**Comment by Blinkaji** [comment]
Sid: Dynamic Table Patch

**Comment by Blinkaji** [comment]
Sid: Print Reports

**Comment by Blinkaji** [comment]
Sid: Change File is Jank
